baseURL = "https://neerazz.github.io/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Neeraj"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "My Work"
url = "#service"
weight = 3
# [[menu.main]]
# name = "Awards & Recognition"
# url = "#blog"
# weight = 4
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "/#about"
weight = 1
[[menu.sitemap]]
name = "Contact"
url = "/contact"
weight = 2
[[menu.sitemap]]
name = "Work"
url = "#service"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2021"
footerLogo = "images/contact/widget-logo.png"
# formspreeURL = "YOUR FORMSPREE URL"
# googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "10410 Highland Manor Dr, Tampa, FL 33610"
email = "b.neerajkumarsingh@gmail.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(1) 724-NEERAJ-0"

[params.map]
APIkey = "AIzaSyBcj-CHmXBuE3yGrqMzorjZZkGtb127LNU"
latitude = "27.987025102504646"
longitude = "-82.32838968470132"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/neerazz"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-hacker-news"
url = "https://leetcode.com/neerazz90/"
weight = 3
# [[params.social]]
# icon = "fa-twitter-square"
# url = "https://twitter.com/"